version: '3.8'

services:
  nestjs:
    build: .
    ports:
      - "3001:3001"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
      - DB_HOST=db 
      - DB_PORT=3308
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_DATABASE=Chat
      - PORT= 3001
    depends_on:
      - db
  db:
    image: mysql:latest
    container_name: chat_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./data:/var/lib/mysql